name: grunt_gen_example
description: A sample project showcase generating workers
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.9.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  build_web_compilers: ^2.16.0
  grunt_web_worker_gen: any
  worker_service: any
  sunny_services: any
  pfile: any
  flutter:
    sdk: flutter

dependency_overrides:
  pfile:
    path: ../../../pfile
  grunt_web_worker_gen:
    path: ../
  sunny_dart:
    path: ../../../sunny_dart

  sunny_services:
    path: ../../../sunny_services

  worker_service:
    path: ../../
  reliveit:
    path: ../../../sunny_entities/reliveit
  contact_v2:
    path: ../../../sunny_entities/contact_v2
  sunny_fluro:
    path: ../../../sunny_fluro
  meta_forms:
    path: ../../../meta_forms
  sunny_main:
    path: ../../../sunny_entities/sunny_main
  floor_generator: ^0.18.0
  full_text_search:
    path: ../../../full_text_search
  #  observable_collections:
  #    path: ../../../observable_collections
  progress_indicator_button:
    path: ../../../progress_button
  sunny_core_widgets:
    path: ../../../sunny_core_widgets
  sunny_sdk_core:
    path: ../../../sunny_sdk_core
  #  flutter_platform_widgets:
  #    path: ../../../flutter_platform_widgets
  flutter_chips_input_sunny:
    path: ../../../flutter_chips_input_sunny
  waypoints:
    path: ../../../sunny_entities/waypoints
  sunny:
    path: ../../../sunny_entities/sunny
  fact_schemas:
    path: ../../../sunny_entities/fact_schemas
  facts:
    path: ../../../sunny_entities/facts
  sunny_forms:
    path: ../../../sunny_forms
  m_entity:
    path: ../../../sunny_entities/m_entity
  smart_dates:
    path: ../../../sunny_entities/smart_dates
  sunny_data:
    path: ../../../sunny_data
  flutter_platform_widgets:
    path: ../../../flutter_platform_widgets

dev_dependencies:
  build_config: ^0.4.5
  build_runner: ^1.10.13
#  build_web_compilers: ^2.16.0

flutter:
  assets:
    - ancient_task.grunt.dart.js